-- Create patient_panel table for denormalized patient reporting
CREATE TABLE IF NOT EXISTS patient_panel (
    patient_id INTEGER PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    date_of_birth TEXT,
    gender TEXT,
    phone_primary TEXT,
    email TEXT,
    address_street TEXT,
    address_city TEXT,
    address_state TEXT,
    address_zip TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    insurance_primary TEXT,
    insurance_policy_number TEXT,
    status TEXT,
    enrollment_date TEXT,
    discharge_date TEXT,
    notes TEXT,
    created_date TEXT,
    updated_date TEXT,
    current_facility_id INT,
    hypertension INT,
    mental_health_concerns INT,
    dementia INT,
    last_annual_wellness_visit TEXT,
    provider_id INTEGER,
    provider_name TEXT,
    coordinator_id INTEGER,
    coordinator_name TEXT,
    stage1_complete INTEGER,
    stage2_complete INTEGER,
    initial_tv_completed INTEGER,
    initial_tv_completed_date TEXT,
    initial_tv_notes TEXT,
    -- Audit columns
    source_table TEXT,
    source_column TEXT
);