-- ============================================================================
-- CREATE PATIENT TABLES
-- ============================================================================
-- Purpose: Create all patient-related tables for ZMO import
-- Run ONCE to create schemas, then populate via transform_production_data_v3.py
-- ============================================================================
-- patients table (102 columns - complete patient master data)
CREATE TABLE IF NOT EXISTS patients (
    patient_id TEXT PRIMARY KEY,
    region_id TEXT,
    first_name TEXT,
    last_name TEXT,
    date_of_birth TEXT,
    gender TEXT,
    phone_primary TEXT,
    phone_secondary TEXT,
    email TEXT,
    address_street TEXT,
    address_city TEXT,
    address_state TEXT,
    address_zip TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    emergency_contact_relationship TEXT,
    insurance_primary TEXT,
    insurance_policy_number TEXT,
    insurance_secondary TEXT,
    medical_record_number TEXT,
    enrollment_date TEXT,
    discharge_date TEXT,
    notes TEXT,
    created_date TEXT DEFAULT (datetime('now')),
    updated_date TEXT DEFAULT (datetime('now')),
    created_by TEXT,
    updated_by TEXT,
    current_facility_id INTEGER,
    hypertension INTEGER DEFAULT 0,
    mental_health_concerns INTEGER DEFAULT 0,
    dementia INTEGER DEFAULT 0,
    last_annual_wellness_visit TEXT,
    last_first_dob TEXT,
    status TEXT DEFAULT 'Active',
    medical_records_requested INTEGER DEFAULT 0,
    referral_documents_received INTEGER DEFAULT 0,
    insurance_cards_received INTEGER DEFAULT 0,
    emed_signature_received INTEGER DEFAULT 0,
    last_visit_date TEXT,
    facility TEXT,
    assigned_coordinator_id INTEGER,
    er_count_1yr INTEGER,
    hospitalization_count_1yr INTEGER,
    clinical_biometric TEXT,
    chronic_conditions_provider TEXT,
    cancer_history TEXT,
    subjective_risk_level TEXT,
    provider_mh_schizophrenia INTEGER DEFAULT 0,
    provider_mh_depression INTEGER DEFAULT 0,
    provider_mh_anxiety INTEGER DEFAULT 0,
    provider_mh_stress INTEGER DEFAULT 0,
    provider_mh_adhd INTEGER DEFAULT 0,
    provider_mh_bipolar INTEGER DEFAULT 0,
    provider_mh_suicidal INTEGER DEFAULT 0,
    active_specialists TEXT,
    code_status TEXT,
    cognitive_function TEXT,
    functional_status TEXT,
    goals_of_care TEXT,
    active_concerns TEXT,
    initial_tv_completed_date TEXT,
    initial_tv_notes TEXT,
    service_type TEXT,
    tv_time TEXT,
    eligibility_status TEXT,
    eligibility_notes TEXT,
    eligibility_verified INTEGER DEFAULT 0,
    emed_chart_created INTEGER DEFAULT 0,
    chart_id TEXT,
    facility_confirmed INTEGER DEFAULT 0,
    chart_notes TEXT,
    intake_call_completed INTEGER DEFAULT 0,
    intake_notes TEXT,
    goc_value TEXT,
    appointment_contact_name TEXT,
    appointment_contact_phone TEXT,
    appointment_contact_email TEXT,
    medical_contact_name TEXT,
    medical_contact_phone TEXT,
    medical_contact_email TEXT,
    primary_care_provider TEXT,
    pcp_last_seen TEXT,
    active_specialist TEXT,
    specialist_last_seen TEXT,
    chronic_conditions_onboarding TEXT,
    mh_schizophrenia INTEGER DEFAULT 0,
    mh_depression INTEGER DEFAULT 0,
    mh_anxiety INTEGER DEFAULT 0,
    mh_stress INTEGER DEFAULT 0,
    mh_adhd INTEGER DEFAULT 0,
    mh_bipolar INTEGER DEFAULT 0,
    mh_suicidal INTEGER DEFAULT 0,
    tv_date TEXT,
    tv_scheduled INTEGER DEFAULT 0,
    patient_notified INTEGER DEFAULT 0,
    initial_tv_provider TEXT
);
-- patient_panel table (92 columns - dashboard display)
CREATE TABLE IF NOT EXISTS patient_panel (
    patient_id TEXT PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    date_of_birth TEXT,
    gender TEXT,
    phone_primary TEXT,
    phone_secondary TEXT,
    email TEXT,
    address_street TEXT,
    address_city TEXT,
    address_state TEXT,
    address_zip TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    emergency_contact_relationship TEXT,
    insurance_primary TEXT,
    insurance_policy_number TEXT,
    insurance_secondary TEXT,
    medical_record_number TEXT,
    enrollment_date TEXT,
    discharge_date TEXT,
    notes TEXT,
    created_date TEXT DEFAULT (datetime('now')),
    updated_date TEXT DEFAULT (datetime('now')),
    created_by TEXT,
    updated_by TEXT,
    current_facility_id INTEGER,
    hypertension INTEGER DEFAULT 0,
    mental_health_concerns INTEGER DEFAULT 0,
    dementia INTEGER DEFAULT 0,
    last_annual_wellness_visit TEXT,
    last_first_dob TEXT,
    status TEXT DEFAULT 'Active',
    medical_records_requested INTEGER DEFAULT 0,
    referral_documents_received INTEGER DEFAULT 0,
    insurance_cards_received INTEGER DEFAULT 0,
    emed_signature_received INTEGER DEFAULT 0,
    last_visit_date TEXT,
    facility TEXT,
    assigned_coordinator_id INTEGER,
    er_count_1yr INTEGER,
    hospitalization_count_1yr INTEGER,
    clinical_biometric TEXT,
    chronic_conditions_provider TEXT,
    cancer_history TEXT,
    subjective_risk_level TEXT,
    provider_mh_schizophrenia INTEGER DEFAULT 0,
    provider_mh_depression INTEGER DEFAULT 0,
    provider_mh_anxiety INTEGER DEFAULT 0,
    provider_mh_stress INTEGER DEFAULT 0,
    provider_mh_adhd INTEGER DEFAULT 0,
    provider_mh_bipolar INTEGER DEFAULT 0,
    provider_mh_suicidal INTEGER DEFAULT 0,
    active_specialists TEXT,
    code_status TEXT,
    cognitive_function TEXT,
    functional_status TEXT,
    goals_of_care TEXT,
    active_concerns TEXT,
    initial_tv_completed_date TEXT,
    initial_tv_notes TEXT,
    initial_tv_provider TEXT,
    provider_id INTEGER,
    provider_name TEXT,
    coordinator_id INTEGER,
    coordinator_name TEXT,
    stage1_complete INTEGER DEFAULT 0,
    stage2_complete INTEGER DEFAULT 0,
    initial_tv_completed INTEGER DEFAULT 0,
    source_table TEXT,
    source_column TEXT,
    last_visit_provider_id INTEGER,
    last_visit_provider_name TEXT,
    last_visit_service_type TEXT,
    region_id TEXT,
    eligibility_status TEXT,
    eligibility_notes TEXT,
    eligibility_verified INTEGER DEFAULT 0,
    emed_chart_created INTEGER DEFAULT 0,
    chart_id TEXT,
    facility_confirmed INTEGER DEFAULT 0,
    chart_notes TEXT,
    intake_call_completed INTEGER DEFAULT 0,
    intake_notes TEXT,
    task_date TEXT,
    goc_value TEXT
);
-- patient_assignments table (provider/coordinator assignments)
CREATE TABLE IF NOT EXISTS patient_assignments (
    assignment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id TEXT,
    provider_id INTEGER,
    coordinator_id INTEGER,
    assignment_date TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (provider_id) REFERENCES users(user_id),
    FOREIGN KEY (coordinator_id) REFERENCES users(user_id)
);
-- onboarding_patients table (onboarding workflow tracking)
CREATE TABLE IF NOT EXISTS onboarding_patients (
    onboarding_id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id TEXT,
    first_name TEXT,
    last_name TEXT,
    date_of_birth TEXT,
    phone_primary TEXT,
    email TEXT,
    hypertension BOOLEAN DEFAULT FALSE,
    mental_health_concerns BOOLEAN DEFAULT FALSE,
    dementia BOOLEAN DEFAULT FALSE,
    annual_well_visit DATE,
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    tv_date DATE,
    tv_time TIME,
    tv_scheduled BOOLEAN DEFAULT FALSE,
    assigned_provider_user_id INTEGER,
    patient_notified BOOLEAN DEFAULT FALSE,
    eligibility_status TEXT,
    eligibility_notes TEXT,
    eligibility_verified BOOLEAN DEFAULT FALSE,
    emed_chart_created BOOLEAN DEFAULT FALSE,
    chart_id TEXT,
    facility_confirmed BOOLEAN DEFAULT FALSE,
    chart_notes TEXT,
    intake_call_completed BOOLEAN DEFAULT FALSE,
    intake_notes TEXT,
    initial_tv_completed BOOLEAN DEFAULT FALSE,
    assigned_coordinator_user_id INTEGER,
    initial_tv_completed_date TEXT,
    initial_tv_notes TEXT,
    initial_tv_provider TEXT,
    provider_completed_initial_tv BOOLEAN DEFAULT FALSE,
    visit_type TEXT DEFAULT 'Home Visit',
    billing_code TEXT DEFAULT '99345',
    duration_minutes INTEGER DEFAULT 45,
    mh_schizophrenia BOOLEAN DEFAULT FALSE,
    mh_depression BOOLEAN DEFAULT FALSE,
    mh_anxiety BOOLEAN DEFAULT FALSE,
    mh_stress BOOLEAN DEFAULT FALSE,
    mh_adhd BOOLEAN DEFAULT FALSE,
    mh_bipolar BOOLEAN DEFAULT FALSE,
    mh_suicidal BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (assigned_provider_user_id) REFERENCES users(user_id),
    FOREIGN KEY (assigned_coordinator_user_id) REFERENCES users(user_id)
);
-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_patients_status ON patients(status);
CREATE INDEX IF NOT EXISTS idx_patients_facility ON patients(current_facility_id);
CREATE INDEX IF NOT EXISTS idx_patient_panel_status ON patient_panel(status);
CREATE INDEX IF NOT EXISTS idx_patient_assignments_patient ON patient_assignments(patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_assignments_provider ON patient_assignments(provider_id);
CREATE INDEX IF NOT EXISTS idx_patient_assignments_coordinator ON patient_assignments(coordinator_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_patient ON onboarding_patients(patient_id);
SELECT 'Patient tables created successfully' as status;