-- Create views to bridge monthly partitioned tables with dashboard expectations
-- Dashboards expect provider_tasks and coordinator_tasks (non-partitioned)
-- But we have provider_tasks_YYYY_MM and coordinator_tasks_YYYY_MM (partitioned)
-- Drop existing views if they exist
DROP VIEW IF EXISTS provider_tasks;
DROP VIEW IF EXISTS coordinator_tasks;
-- Create provider_tasks view (UNION ALL monthly tables)
CREATE VIEW provider_tasks AS
SELECT *
FROM provider_tasks_2023_05
UNION ALL
SELECT *
FROM provider_tasks_2023_06
UNION ALL
SELECT *
FROM provider_tasks_2023_07
UNION ALL
SELECT *
FROM provider_tasks_2023_10
UNION ALL
SELECT *
FROM provider_tasks_2023_11
UNION ALL
SELECT *
FROM provider_tasks_2023_12
UNION ALL
SELECT *
FROM provider_tasks_2024_01
UNION ALL
SELECT *
FROM provider_tasks_2024_02
UNION ALL
SELECT *
FROM provider_tasks_2024_03
UNION ALL
SELECT *
FROM provider_tasks_2024_04
UNION ALL
SELECT *
FROM provider_tasks_2024_05
UNION ALL
SELECT *
FROM provider_tasks_2024_06
UNION ALL
SELECT *
FROM provider_tasks_2024_07
UNION ALL
SELECT *
FROM provider_tasks_2024_08
UNION ALL
SELECT *
FROM provider_tasks_2024_09
UNION ALL
SELECT *
FROM provider_tasks_2024_10
UNION ALL
SELECT *
FROM provider_tasks_2024_11
UNION ALL
SELECT *
FROM provider_tasks_2024_12
UNION ALL
SELECT *
FROM provider_tasks_2025_01
UNION ALL
SELECT *
FROM provider_tasks_2025_02
UNION ALL
SELECT *
FROM provider_tasks_2025_03
UNION ALL
SELECT *
FROM provider_tasks_2025_04
UNION ALL
SELECT *
FROM provider_tasks_2025_05
UNION ALL
SELECT *
FROM provider_tasks_2025_06
UNION ALL
SELECT *
FROM provider_tasks_2025_07
UNION ALL
SELECT *
FROM provider_tasks_2025_08
UNION ALL
SELECT *
FROM provider_tasks_2025_09
UNION ALL
SELECT *
FROM provider_tasks_2025_10
UNION ALL
SELECT *
FROM provider_tasks_2025_11;
-- Create coordinator_tasks view (UNION ALL monthly tables)
CREATE VIEW coordinator_tasks AS
SELECT *
FROM coordinator_tasks_2025_01
UNION ALL
SELECT *
FROM coordinator_tasks_2025_02
UNION ALL
SELECT *
FROM coordinator_tasks_2025_03
UNION ALL
SELECT *
FROM coordinator_tasks_2025_04
UNION ALL
SELECT *
FROM coordinator_tasks_2025_05
UNION ALL
SELECT *
FROM coordinator_tasks_2025_06
UNION ALL
SELECT *
FROM coordinator_tasks_2025_07
UNION ALL
SELECT *
FROM coordinator_tasks_2025_08
UNION ALL
SELECT *
FROM coordinator_tasks_2025_09
UNION ALL
SELECT *
FROM coordinator_tasks_2025_10
UNION ALL
SELECT *
FROM coordinator_tasks_2025_11;