-- Migration Script: Update task_billing_codes to customer specification
-- Date: 2025-01-13
--
-- This script:
-- 1. Drops problematic views that reference non-existent columns
-- 2. Renames existing task_billing_codes to reference_only_task_billing_codes
-- 3. Creates new task_billing_codes table with updated schema
-- 4. Populates with customer-specified PCP visit billing codes

-- ============================================================================
-- STEP 1: Drop ALL views that might reference task_billing_codes or unified_tasks
-- ============================================================================

-- Drop all views in correct dependency order
DROP VIEW IF EXISTS minutes_per_staff_per_month_per_facility;
DROP VIEW IF EXISTS tasks_per_month_per_facility;
DROP VIEW IF EXISTS monthly_trends;
DROP VIEW IF EXISTS staff_performance_summary;
DROP VIEW IF EXISTS facility_summary;
DROP VIEW IF EXISTS unified_tasks_with_facilities;
DROP VIEW IF EXISTS unified_tasks;
-- Note: provider_tasks and coordinator_tasks union views are NOT recreated here
-- They are auto-generated by the database.py based on monthly tables

-- ============================================================================
-- STEP 2: Rename existing table to reference_only (if it exists)
-- ============================================================================

-- Drop the reference table if it already exists (from previous migration attempts)
DROP TABLE IF EXISTS reference_only_task_billing_codes;

-- Rename the existing task_billing_codes table (if it exists)
-- Note: If table was already dropped, we skip this step
-- SQLite doesn't support IF EXISTS with ALTER TABLE, so we use a try-catch approach
-- The script below will fail if task_billing_codes doesn't exist, but that's OK

-- ============================================================================
-- STEP 3: Create new task_billing_codes table with customer-specified schema
-- ============================================================================

CREATE TABLE task_billing_codes (
    code_id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_description TEXT NOT NULL,
    service_type TEXT NOT NULL,
    location_type TEXT NOT NULL,
    patient_type TEXT NOT NULL,
    min_minutes INTEGER NOT NULL,
    max_minutes INTEGER NOT NULL,
    billing_code TEXT NOT NULL,
    description TEXT,
    rate DECIMAL(10,2),
    effective_date TEXT NOT NULL DEFAULT (date('now')),
    expiration_date TEXT,
    created_date TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Create indexes for lookups
CREATE INDEX idx_task_billing_codes_service ON task_billing_codes(service_type);
CREATE INDEX idx_task_billing_codes_location ON task_billing_codes(location_type);
CREATE INDEX idx_task_billing_codes_patient_type ON task_billing_codes(patient_type);
CREATE INDEX idx_task_billing_codes_code ON task_billing_codes(billing_code);

-- ============================================================================
-- STEP 4: Populate with customer-specified billing codes
-- ============================================================================

-- Home Visits - Board&Care/GroupHome (HO)
INSERT INTO task_billing_codes (task_description, service_type, location_type, patient_type, min_minutes, max_minutes, billing_code, description, rate, effective_date) VALUES
('PCP-Visit Board&Care/GroupHome (HO) (NEW pt)', 'Primary Care Visit', 'Home', 'New Patient', 100, 109, '99345 G0318x1', 'PCP-Visit Board&Care/GroupHome (HO) (NEW pt) - Home - New Patient (100-109 mins)', 250.00, '2025-01-01'),
('PCP-Visit Board&Care/GroupHome (HO) (NEW pt)', 'Primary Care Visit', 'Home', 'New Patient', 90, 99, '99344 G0318x1', 'PCP-Visit Board&Care/GroupHome (HO) (NEW pt) - Home - New Patient (90-99 mins)', 230.00, '2025-01-01'),
('PCP-Visit Board&Care/GroupHome (HO) (NEW pt)', 'Primary Care Visit', 'Home', 'New Patient', 70, 89, '99343 G0318x1', 'PCP-Visit Board&Care/GroupHome (HO) (NEW pt) - Home - New Patient (70-89 mins)', 210.00, '2025-01-01'),
('PCP-Visit Board&Care/GroupHome (HO) (NEW pt)', 'Primary Care Visit', 'Home', 'New Patient', 60, 69, '99342 G0318x1', 'PCP-Visit Board&Care/GroupHome (HO) (NEW pt) - Home - New Patient (60-69 mins)', 200.00, '2025-01-01'),
('PCP-Visit Board&Care/GroupHome (HO) (NEW pt)', 'Primary Care Visit', 'Home', 'New Patient', 40, 59, '99341 G0318x1', 'PCP-Visit Board&Care/GroupHome (HO) (NEW pt) - Home - New Patient (40-59 mins)', 180.00, '2025-01-01'),

('PCP-Visit Board&Care/GroupHome (HO) (ESTAB pt)', 'Primary Care Visit', 'Home', 'Established Patient', 100, 109, '99350 G0318x2', 'PCP-Visit Board&Care/GroupHome (HO) (ESTAB pt) - Home - Established Patient (100-109 mins)', 250.00, '2025-01-01'),
('PCP-Visit Board&Care/GroupHome (HO) (ESTAB pt)', 'Primary Care Visit', 'Home', 'Established Patient', 90, 99, '99349 G0318x2', 'PCP-Visit Board&Care/GroupHome (HO) (ESTAB pt) - Home - Established Patient (90-99 mins)', 230.00, '2025-01-01'),
('PCP-Visit Board&Care/GroupHome (HO) (ESTAB pt)', 'Primary Care Visit', 'Home', 'Established Patient', 70, 89, '99348 G0318x2', 'PCP-Visit Board&Care/GroupHome (HO) (ESTAB pt) - Home - Established Patient (70-89 mins)', 210.00, '2025-01-01'),
('PCP-Visit Board&Care/GroupHome (HO) (ESTAB pt)', 'Primary Care Visit', 'Home', 'Established Patient', 60, 69, '99347 G0318x2', 'PCP-Visit Board&Care/GroupHome (HO) (ESTAB pt) - Home - Established Patient (60-69 mins)', 200.00, '2025-01-01'),
('PCP-Visit Board&Care/GroupHome (HO) (ESTAB pt)', 'Primary Care Visit', 'Home', 'Established Patient', 40, 59, '99347 G0318x2', 'PCP-Visit Board&Care/GroupHome (HO) (ESTAB pt) - Home - Established Patient (40-59 mins)', 180.00, '2025-01-01'),

-- Office Visits (OF)
('PCP-Visit Office (OF) (NEW pt)', 'Primary Care Visit', 'Office', 'New Patient', 60, 69, '99205', 'PCP-Visit Office (OF) (NEW pt) - Office - New Patient (60-69 mins)', 250.00, '2025-01-01'),
('PCP-Visit Office (OF) (NEW pt)', 'Primary Care Visit', 'Office', 'New Patient', 50, 59, '99204', 'PCP-Visit Office (OF) (NEW pt) - Office - New Patient (50-59 mins)', 230.00, '2025-01-01'),
('PCP-Visit Office (OF) (NEW pt)', 'Primary Care Visit', 'Office', 'New Patient', 40, 49, '99204', 'PCP-Visit Office (OF) (NEW pt) - Office - New Patient (40-49 mins)', 210.00, '2025-01-01'),
('PCP-Visit Office (OF) (NEW pt)', 'Primary Care Visit', 'Office', 'New Patient', 30, 39, '99203', 'PCP-Visit Office (OF) (NEW pt) - Office - New Patient (30-39 mins)', 180.00, '2025-01-01'),
('PCP-Visit Office (OF) (NEW pt)', 'Primary Care Visit', 'Office', 'New Patient', 20, 29, '99202', 'PCP-Visit Office (OF) (NEW pt) - Office - New Patient (20-29 mins)', 150.00, '2025-01-01'),
('PCP-Visit Office (OF) (NEW pt)', 'Primary Care Visit', 'Office', 'New Patient', 10, 19, '99201', 'PCP-Visit Office (OF) (NEW pt) - Office - New Patient (10-19 mins)', 120.00, '2025-01-01'),

('PCP-Visit Office (OF) (ESTAB pt)', 'Primary Care Visit', 'Office', 'Established Patient', 40, 49, '99215', 'PCP-Visit Office (OF) (ESTAB pt) - Office - Established Patient (40-49 mins)', 180.00, '2025-01-01'),
('PCP-Visit Office (OF) (ESTAB pt)', 'Primary Care Visit', 'Office', 'Established Patient', 30, 39, '99214', 'PCP-Visit Office (OF) (ESTAB pt) - Office - Established Patient (30-39 mins)', 150.00, '2025-01-01'),
('PCP-Visit Office (OF) (ESTAB pt)', 'Primary Care Visit', 'Office', 'Established Patient', 20, 29, '99213', 'PCP-Visit Office (OF) (ESTAB pt) - Office - Established Patient (20-29 mins)', 130.00, '2025-01-01'),
('PCP-Visit Office (OF) (ESTAB pt)', 'Primary Care Visit', 'Office', 'Established Patient', 15, 19, '99212', 'PCP-Visit Office (OF) (ESTAB pt) - Office - Established Patient (15-19 mins)', 110.00, '2025-01-01'),
('PCP-Visit Office (OF) (ESTAB pt)', 'Primary Care Visit', 'Office', 'Established Patient', 10, 14, '99212', 'PCP-Visit Office (OF) (ESTAB pt) - Office - Established Patient (10-14 mins)', 100.00, '2025-01-01'),

-- Telehealth Visits (TE)
('PCP-Visit Telehealth (TE) (NEW pt)', 'Primary Care Visit', 'Telehealth', 'New Patient', 40, 49, '99204', 'PCP-Visit Telehealth (TE) (NEW pt) - Telehealth - New Patient (40-49 mins)', 210.00, '2025-01-01'),
('PCP-Visit Telehealth (TE) (NEW pt)', 'Primary Care Visit', 'Telehealth', 'New Patient', 30, 39, '99203', 'PCP-Visit Telehealth (TE) (NEW pt) - Telehealth - New Patient (30-39 mins)', 180.00, '2025-01-01'),
('PCP-Visit Telehealth (TE) (NEW pt)', 'Primary Care Visit', 'Telehealth', 'New Patient', 20, 29, '99202', 'PCP-Visit Telehealth (TE) (NEW pt) - Telehealth - New Patient (20-29 mins)', 150.00, '2025-01-01'),
('PCP-Visit Telehealth (TE) (NEW pt)', 'Primary Care Visit', 'Telehealth', 'New Patient', 10, 19, '99201', 'PCP-Visit Telehealth (TE) (NEW pt) - Telehealth - New Patient (10-19 mins)', 120.00, '2025-01-01'),

('PCP-Visit Telehealth (TE) (ESTAB pt)', 'Primary Care Visit', 'Telehealth', 'Established Patient', 30, 39, '99214', 'PCP-Visit Telehealth (TE) (ESTAB pt) - Telehealth - Established Patient (30-39 mins)', 150.00, '2025-01-01'),
('PCP-Visit Telehealth (TE) (ESTAB pt)', 'Primary Care Visit', 'Telehealth', 'Established Patient', 20, 29, '99213', 'PCP-Visit Telehealth (TE) (ESTAB pt) - Telehealth - Established Patient (20-29 mins)', 130.00, '2025-01-01'),
('PCP-Visit Telehealth (TE) (ESTAB pt)', 'Primary Care Visit', 'Telehealth', 'Established Patient', 10, 19, '99212', 'PCP-Visit Telehealth (TE) (ESTAB pt) - Telehealth - Established Patient (10-19 mins)', 110.00, '2025-01-01'),
('PCP-Visit Telehealth (TE) (ESTAB pt)', 'Primary Care Visit', 'Telehealth', 'Established Patient', 5, 9, '99211', 'PCP-Visit Telehealth (TE) (ESTAB pt) - Telehealth - Established Patient (5-9 mins)', 90.00, '2025-01-01'),

-- Home Visits (HO) - standard home visits (not Board&Care)
('PCP-Visit Home (HO) (NEW pt)', 'Primary Care Visit', 'Home', 'New Patient', 100, 109, '99345 G0318x1', 'PCP-Visit Home (HO) (NEW pt) - Home - New Patient (100-109 mins)', 250.00, '2025-01-01'),
('PCP-Visit Home (HO) (NEW pt)', 'Primary Care Visit', 'Home', 'New Patient', 90, 99, '99344 G0318x1', 'PCP-Visit Home (HO) (NEW pt) - Home - New Patient (90-99 mins)', 230.00, '2025-01-01'),
('PCP-Visit Home (HO) (NEW pt)', 'Primary Care Visit', 'Home', 'New Patient', 70, 89, '99343 G0318x1', 'PCP-Visit Home (HO) (NEW pt) - Home - New Patient (70-89 mins)', 210.00, '2025-01-01'),
('PCP-Visit Home (HO) (NEW pt)', 'Primary Care Visit', 'Home', 'New Patient', 60, 69, '99342 G0318x1', 'PCP-Visit Home (HO) (NEW pt) - Home - New Patient (60-69 mins)', 200.00, '2025-01-01'),
('PCP-Visit Home (HO) (NEW pt)', 'Primary Care Visit', 'Home', 'New Patient', 40, 59, '99341 G0318x1', 'PCP-Visit Home (HO) (NEW pt) - Home - New Patient (40-59 mins)', 180.00, '2025-01-01'),

('PCP-Visit Home (HO) (ESTAB pt)', 'Primary Care Visit', 'Home', 'Established Patient', 100, 109, '99350 G0318x2', 'PCP-Visit Home (HO) (ESTAB pt) - Home - Established Patient (100-109 mins)', 250.00, '2025-01-01'),
('PCP-Visit Home (HO) (ESTAB pt)', 'Primary Care Visit', 'Home', 'Established Patient', 90, 99, '99349 G0318x2', 'PCP-Visit Home (HO) (ESTAB pt) - Home - Established Patient (90-99 mins)', 230.00, '2025-01-01'),
('PCP-Visit Home (HO) (ESTAB pt)', 'Primary Care Visit', 'Home', 'Established Patient', 70, 89, '99348 G0318x2', 'PCP-Visit Home (HO) (ESTAB pt) - Home - Established Patient (70-89 mins)', 210.00, '2025-01-01'),
('PCP-Visit Home (HO) (ESTAB pt)', 'Primary Care Visit', 'Home', 'Established Patient', 60, 69, '99347 G0318x2', 'PCP-Visit Home (HO) (ESTAB pt) - Home - Established Patient (60-69 mins)', 200.00, '2025-01-01'),
('PCP-Visit Home (HO) (ESTAB pt)', 'Primary Care Visit', 'Home', 'Established Patient', 40, 59, '99347 G0318x2', 'PCP-Visit Home (HO) (ESTAB pt) - Home - Established Patient (40-59 mins)', 180.00, '2025-01-01'),

-- Phone/Video Reviews
('Phone review', 'Communication', 'Remote', 'Established Patient', 5, 15, '99441', 'Phone review - 5-10 minutes', 50.00, '2025-01-01'),
('Phone review', 'Communication', 'Remote', 'Established Patient', 11, 20, '99442', 'Phone review - 11-20 minutes', 75.00, '2025-01-01'),
('Phone review', 'Communication', 'Remote', 'Established Patient', 21, 30, '99443', 'Phone review - 21-30 minutes', 100.00, '2025-01-01'),

-- Care Coordination codes (retained for coordinators)
('Care Coordination', 'Care Coordination', 'Office', 'Established Patient', 5, 19, '99490', 'Care coordination - 5-19 minutes', 75.00, '2025-01-01'),
('Care Coordination', 'Care Coordination', 'Office', 'Established Patient', 20, 49, '99491', 'Care coordination - Moderate (20-49 mins)', 150.00, '2025-01-01'),
('Care Coordination', 'Care Coordination', 'Office', 'Established Patient', 50, 99, '99492', 'Care coordination - Complex (50-99 mins)', 250.00, '2025-01-01'),

-- Not Billable
('Not Billable', 'N/A', 'N/A', 'N/A', 0, 0, 'NOT_BILLABLE', 'Task is not billable', 0.00, '2025-01-01');

-- ============================================================================
-- STEP 5: Recreate the unified_tasks view without problematic columns
-- ============================================================================

CREATE VIEW unified_tasks AS
-- Coordinator tasks
SELECT
    'coordinator' AS task_type,
    coordinator_task_id AS task_id,
    coordinator_id AS staff_id,
    coordinator_name AS staff_name,
    patient_id,
    NULL AS patient_name,
    task_date,
    duration_minutes AS minutes,
    task_type AS activity_type,
    notes,
    NULL AS task_description,
    NULL AS billing_code,
    NULL AS billing_code_description,
    source_system,
    imported_at,
    NULL AS status,
    NULL AS is_deleted
FROM coordinator_tasks

UNION ALL

-- Provider tasks
SELECT
    'provider' AS task_type,
    provider_task_id AS task_id,
    provider_id AS staff_id,
    provider_name AS staff_name,
    patient_id,
    patient_name,
    task_date,
    minutes_of_service AS minutes,
    NULL AS activity_type,
    notes,
    task_description,
    billing_code,
    billing_code_description,
    source_system,
    imported_at,
    status,
    is_deleted
FROM provider_tasks;

-- ============================================================================
-- STEP 6: Recreate dependent views
-- ============================================================================

CREATE VIEW unified_tasks_with_facilities AS
SELECT
    ut.*,
    p.current_facility_id,
    f.facility_name
FROM unified_tasks ut
LEFT JOIN patients p ON ut.patient_id = p.patient_id
LEFT JOIN facilities f ON p.current_facility_id = f.facility_id;

CREATE VIEW tasks_per_month_per_facility AS
SELECT
    COALESCE(facility_name, 'Unknown Facility') AS facility_name,
    task_type,
    strftime('%Y-%m', task_date) AS month,
    COUNT(*) AS task_count,
    SUM(minutes) AS total_minutes,
    COUNT(DISTINCT staff_name) AS unique_staff,
    COUNT(DISTINCT patient_id) AS unique_patients
FROM unified_tasks_with_facilities
WHERE task_date >= date('now', '-24 months')
GROUP BY facility_name, task_type, month
ORDER BY facility_name, month DESC, task_type;
