-- Standardized Patient ID Normalization Function
-- This file contains the standardized patient ID normalization pattern
-- that should be used consistently across all transformation scripts.

-- STANDARDIZED PATIENT ID NORMALIZATION PATTERN:
-- Use this exact pattern for all patient ID normalization:
--
-- TRIM(
--     REPLACE(
--         REPLACE(
--             REPLACE(
--                 TRIM(REPLACE(source_field, 'ZEN-', '')),
--                 ', ',
--                 ' '
--             ),
--             ',',
--             ' '
--         ),
--         '  ',
--         ' '
--     )
-- )
--
-- This pattern:
-- 1. Removes 'ZEN-' prefix if present
-- 2. Converts comma-space (', ') to single space (' ')
-- 3. Converts comma (',') to single space (' ')
-- 4. Converts double spaces ('  ') to single space (' ')
-- 5. Trims leading/trailing whitespace
--
-- USAGE EXAMPLES:
--
-- For coordinator tasks (from "Pt Name" field):
-- TRIM(
--     REPLACE(
--         REPLACE(
--             REPLACE(
--                 TRIM(REPLACE(t.[Pt Name], 'ZEN-', '')),
--                 ', ',
--                 ' '
--             ),
--             ',',
--             ' '
--         ),
--         '  ',
--         ' '
--     )
-- ) AS patient_id
--
-- For provider tasks (from "Patient Last, First DOB" field):
-- TRIM(
--     REPLACE(
--         REPLACE(
--             REPLACE(
--                 TRIM(REPLACE(t.[Patient Last, First DOB], 'ZEN-', '')),
--                 ', ',
--                 ' '
--             ),
--             ',',
--             ' '
--         ),
--         '  ',
--         ' '
--     )
-- ) AS patient_id
--
-- For patients table (from "LAST FIRST DOB" field):
-- TRIM(
--     REPLACE(
--         REPLACE(
--             REPLACE(
--                 TRIM(spd."LAST FIRST DOB"),
--                 ', ',
--                 ' '
--             ),
--             ',',
--             ' '
--         ),
--         '  ',
--         ' '
--     )
-- ) AS patient_id
--
-- TRANSFORMATION EXAMPLES:
-- Input: "SMITH, JOHN 01/15/1980"    -> Output: "SMITH JOHN 01/15/1980"
-- Input: "JONES,MARY 12/25/1975"     -> Output: "JONES MARY 12/25/1975"
-- Input: "ZEN-DOE, JANE 03/10/1990"  -> Output: "DOE JANE 03/10/1990"
-- Input: "BROWN  MIKE 06/20/1985"    -> Output: "BROWN MIKE 06/20/1985"
--
-- RELIABILITY CONSIDERATIONS:
-- - Handles various comma formats consistently
-- - Removes legacy ZEN- prefixes
-- - Normalizes whitespace for consistent matching
-- - Prevents data inconsistencies between tables
--
-- MAINTAINABILITY CONSIDERATIONS:
-- - Single source of truth for normalization logic
-- - Easy to update across all scripts
-- - Clear documentation of transformation rules
-- - Consistent behavior across all data pipelines
--
-- PERFORMANCE CONSIDERATIONS:
-- - Normalization at transformation time (not query time)
-- - Reduces need for complex joins with multiple TRIM/REPLACE operations
-- - Enables efficient indexing on normalized patient IDs
--
-- LAST UPDATED: 2025-01-27
-- AUTHOR: AI Assistant
-- VERSION: 1.0